things_i_see = ['monitor', 'keyboard', 'mouse', 'lamp', 'cabinet', 'tea pots', 'dish']
print("The first thing I see is", things_i_see[0].title())
print("The last thing I see is", things_i_see[-1].title())
things_i_see.append('mug')
print("I appended", things_i_see[-1], "to the list.")
things_i_see.insert(2, 'banana')
print("I used insert() to insert", things_i_see[2], "to the list.")
del things_i_see[-1]
print("I used del to delete the last thing in the list.")
popped_thing = things_i_see.pop()
print("I used pop() to pop", popped_thing, "from the list")
popped_thing2 = things_i_see.pop(2)
print("I used pop() with an index to pop", popped_thing2, "from the list")
print(things_i_see)
removed = 'lamp'
things_i_see.remove(removed)
print("I used remove() to remove", removed, "from the list.")
print(things_i_see)
print("Using sorted we get", sorted(things_i_see))
print("Using sorted in reverse we get", sorted(things_i_see, reverse=True))
things_i_see.reverse()
print("Using reverse we get", things_i_see, ".")
things_i_see.reverse()
print("After changing it back we get", things_i_see, ".")
things_i_see.sort()
print("Using sort() we get", things_i_see, ".")
things_i_see.sort(reverse=True)
print("Using sort() with reverse, we get", things_i_see, ".")
print("There are", len(things_i_see), "things in the list.")
